version: "3.9"

services:

  ssl_generator_fastapi:
    build:
      context: .
      dockerfile: fastapi/Dockerfile  # Use the Dockerfile that contains the necessary dependencies for SSL generation
    image: fastapi_app:latest
    container_name: fastapi_app_ssl_generator
    volumes:
      - ./:/home/evidently-fastapi
    command: ["./generate_ssl.sh"]  # Run the SSL generation script for Fastapi
    networks:
      - monitoring

  ssl_generator_streamlit:
    build:
      context: streamlit_app  # Use the context for the Streamlit app directory
      dockerfile: Dockerfile  # Use the Dockerfile that contains the necessary dependencies for Streamlit
    image: streamlit_app:latest
    container_name: streamlit_app
    volumes:
      - ./:/home/evidently-fastapi
    command: ["./generate_ssl.sh"]  # Run the SSL generation script for Streamlit
    networks:
      - monitoring

  fastapi_app:
    build:
      context: .
      dockerfile: fastapi/Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
    image: fastapi_app:latest
    container_name: fastapi_app
    restart: always
    volumes:
      - ./:/home/evidently-fastapi
    environment:
      - "MONITORING_DB_HOST=monitoring-db-postgres"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    ports:
      - 5000:5000
    networks:
      - monitoring

  monitoring-db:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: "monitoring_db"
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_MAX_CONNECTIONS: "200"  # maximum connection limit here
    container_name: monitoring-db-postgres
    ports:
    - 5432:5432
    networks:
      - monitoring
    volumes:
      - monitoring_db_data:/var/lib/postgresql/data
      # - ./sql:/docker-entrypoint-initdb.d  # Mount the SQL script as an initialization script to create new user and grant priveleges
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d monitoring_db -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  streamlit_app:
    build:
      context: streamlit_app
      dockerfile: Dockerfile
    image: streamlit_app:latest
    container_name: streamlit_app
    restart: always
    volumes:
      - ./:/home/evidently-fastapi
    environment:
      - FASTAPI_APP_HOST=fastapi_app
    ports:
      - 8501:8501
    networks:
      - monitoring

volumes:
    monitoring_db_data: {}


networks:
  monitoring:
    name: monitoring